
// Expanded common synonyms for rule-based humanization
// Focusing on common academic/formal verbs, adjectives, and adverbs to vary vocabulary.

export const COMMON_SYNONYMS: Record<string, string[]> = {
    // Verbs
    "utilize": ["use", "employ", "apply", "leverage", "harness"],
    "demonstrate": ["show", "prove", "reveal", "display", "exhibit", "illustrate"],
    "facilitate": ["help", "ease", "enable", "promote", "further"],
    "implement": ["execute", "carry out", "enact", "perform", "realize"],
    "subsequently": ["later", "afterwards", "then", "following this"],
    "assist": ["help", "aid", "support", "serve"],
    "attempt": ["try", "strive", "endeavor", "seek"],
    "challenge": ["test", "question", "dispute", "confront"],
    "concept": ["idea", "notion", "theory", "conception"],
    "conclusion": ["end", "closing", "finale", "resolution", "verdict"],
    "ensure": ["make sure", "guarantee", "secure", "assure"],
    "obtain": ["get", "acquire", "gain", "attain"],
    "provide": ["give", "supply", "furnish", "offer", "present"],
    "require": ["need", "entail", "demand", "necessitate"],
    "select": ["choose", "pick", "opt for", "decide on"],
    "terminate": ["end", "stop", "cease", "conclude", "finish"],
    "indicate": ["show", "point out", "signify", "denote"],
    "illustrate": ["show", "demonstrate", "exemplify"],
    "suggest": ["propose", "recommend", "advise", "imply"],
    "establish": ["set up", "found", "institute", "create", "form"],
    "identify": ["spot", "recognize", "pinpoint", "detect"],
    "examine": ["check", "inspect", "study", "analyze", "review"],
    "investigate": ["explore", "examine", "study", "research"],
    "determine": ["decide", "figure out", "conclude", "resolve"],
    "develop": ["grow", "evolve", "advance", "expand", "progress"],
    "enhance": ["improve", "boost", "heighten", "increase"],
    "maintain": ["keep", "preserve", "sustain", "continue"],
    "occur": ["happen", "take place", "arise"],
    "participate": ["take part", "join", "engage"],
    "possess": ["have", "own", "hold"],
    "prevent": ["stop", "hinder", "avert", "block"],
    "purchase": ["buy", "acquire", "get"],
    "receive": ["get", "obtain", "accept"],
    "respond": ["reply", "answer", "react"],

    // Adjectives / Adverbs
    "additionally": ["also", "too", "besides", "moreover", "furthermore"],
    "moreover": ["also", "plus", "furthermore", "what's more"],
    "however": ["but", "yet", "still", "though"],
    "therefore": ["so", "thus", "hence", "accordingly"],
    "approximately": ["about", "around", "roughly", "nearly"],
    "currently": ["now", "at present", "right now"],
    "frequently": ["often", "regularly", "commonly"],
    "immediately": ["at once", "right away", "instantly"],
    "initially": ["at first", "to start with", "originally"],
    "primarily": ["mainly", "mostly", "chiefly"],
    "significantly": ["notably", "considerably", "substantially"],
    "various": ["many", "several", "diverse", "different"],
    "sufficient": ["enough", "adequate", "plenty"],
    "numerous": ["many", "lots of", "countless"],
    "fundamental": ["basic", "core", "essential", "key"],
    "essential": ["crucial", "vital", "key", "important"],
    "critical": ["key", "vital", "crucial", "major"],
    "beneficial": ["helpful", "good", "useful", "advantageous"],
    "detrimental": ["harmful", "bad", "damaging"],
    "significant": ["big", "major", "important", "notable"],
    "effective": ["good", "useful", "successful"],
    "efficient": ["quick", "fast", "productive"],
    "novel": ["new", "fresh", "original", "unique"],
    "appropriate": ["fitting", "suitable", "right", "proper"],
    "incorrect": ["wrong", "false", "inaccurate"],
    "difficult": ["hard", "tough", "challenging"],
    "simple": ["easy", "plain", "uncomplicated"],
    "complex": ["hard", "complicated", "intricate"],
};
